### ISSUE TITLE
Remove white border

### ISSUE THREAD

**Issue by aldrchi** [FHachez/obsidian-convert-url-to-iframe#25]
Please add css property **border: none** to generated embed-code to remove white border around video-player. 
![image](https://user-images.githubusercontent.com/2861454/129898749-0dee40ab-7f6b-484c-becd-53ada7d9d917.png)

**Comment by kankaristo** [comment]
I'm not sure the plugin should do that, since it's not necessarily the only "source" of iframes in Obsidian.

I'm setting the border to none in my custom CSS. I think either that or whatever theme is in use is a better place for this (so that all iframes are displayed the same, whether they're from this plugin or not).

**Comment by aldrchi** [comment]
Thank you for the clarification.
